config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount SolidQueueDashboard::Engine, at: "/solid-queue"

  resources :contents

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
  validates :body, presence: true

  has_one :kernel_command
  has_one_attached :audio

  belongs_to :category

  def run_kernel_command
    system(kernel_command.body)
  end

  def self.sanitize(content)
    sanitised_content = content.gsub("\n", "")
      content.gsub(";", ",")
      .gsub(/£(\d+)trn/, '\1 trillion pounds')
      .gsub(/$(\d+)trn/, '\1 trillion dollars')
      .gsub(/€(\d+)trn/, '\1 trillion euros')
      .gsub(/\£(\d+)bn/, '\1 billion pounds')
      .gsub(/\$(\d+)bn/, '\1 billion dollars')
      .gsub(/\€(\d+)bn/, '\1 billion euros')
      .gsub(/£(\d+)m/, '\1 million pounds')
      .gsub(/\$(\d+)m/, '\1 million dollars')
      .gsub(/€(\d+)m/, '\1 million euros')
      .gsub(/(\d+)m/, '\1 million')
      .gsub(/(\d+)pm/, '\1PM')
      .gsub(/(\d+)am/, '\1AM')
      .gsub(/(\d+)p/, '\1 pee')

    sanitised_content.strip
  end
end

app/models/kernel_command.rb
class KernelCommand < ApplicationRecord
  belongs_to :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
    @pagy, @contents = pagy(@category.contents)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params.expect(:id))
  end

  def category_params
    params.expect(category: [ :name ])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[show edit destroy]

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(
      title: content_params[:title],
      body: Content.sanitize(content_params[:body]),
      category_id: content_params[:category_id]
    )

    if @content.save
      TextToSpeech.perform_later(@content)

      redirect_to contents_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @content.assign_attributes(
      title: content_params[:title],
      body: Content.sanitize(content_params[:body]),
      category_id: content_params[:category_id]
    )

    if @content.save
      TextToSpeech.perform_later(@content)

      redirect_to contents_path
    else
      render :edit
    end
  end

  def destroy
    @content.destroy

    redirect_to category_path(@content.category)
  end

  private

  def set_content
    @content = Content.find(params.require(:id))
  end

  def content_params
    params.require(:content).permit(:body, :title, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

<% @contents.each do |content| %> 
  <h1><%= link_to content.title, edit_content_path(content) %></h1>
  <%= button_to 'Delete', content_path(content), method: :delete %>
  <br>

  <% if content.audio.present? %> 
    <%= audio_tag(content.audio, controls: true) %>
  <% end %> 
<% end %> 

<%# pagy_nav(@pagy) %>

app/views/contents/_form.html.erb
<% content.errors do |error| %>
  <%= "#{errors.type} #{error.message}" %>
<% end %> 

<%= form_with model: content do |form| %>
  <%= form.label :category %>
  <br>
  <br>
  <%= form.select :category_id, Category.all.pluck(:name, :id) %>
  <br>
  <br>
  <%= form.label :title %>
  <br>
  <br>
  <%= form.text_field :title, size: 80 %>
  <br>
  <br>

  <%= form.label :content %>
  <br>
  <br>
  <%= form.text_area :body, cols: 80, rows: 30 %>
  <br>
  <br>
  <%= form.submit %>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit <%= @content.title %></h1>

<%= render "form", content: @content %> 

app/views/contents/index.html.erb
<h1>Contents</h1>
<%= link_to 'New', new_content_path %>

<% Category.all.order(:name).each do |category| %> 
  <h1><%= link_to category.name, category_path(category) %></h1>
<% end %> 

app/views/contents/new.html.erb
<% @content.errors do |error| %>
  <%= "#{errors.type} #{error.message}" %>
<% end %> 

<%= form_with model: @content do |form| %>
  <%= form.label :title %>
  <br>
  <br>
  <%= form.text_field :title %>
  <br>
  <br>

  <%= form.label :content %>
  <br>
  <br>
  <%= form.text_area :body, cols: 40, rows: 10 %>
  <br>
  <br>
  <%= form.submit %>
<% end %>

app/views/contents/show.html.erb
<h1>Contents</h1>

<% if @content.audio.present? %>
  <%= audio_tag(@content.audio, controls: true) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Narator" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>